### ISSUE TITLE
Move the pop-up box a little to the left

### ISSUE THREAD

**Issue by holipay** [0x2E/fusion#17] opened 2024-08-24 06:13 UTC
When I pressed the button in the top right corner of the page (marked as read), the pop-up "Change Successful" blocked me from continuing to press the button. Move the pop-up box a little to the left.

[当我按下页面右上角的按钮（标记已读）之后，弹出的“更改成功”挡住了我继续按下该按钮。请将弹框往左边移动一点。]

**Comment by 0x2E** [comment] 2024-08-24 06:34
Hi. Which device and page? I cannot find a screen size that can reproduce this issue.

**Comment by holipay** [comment] 2024-08-24 06:37
![图片1](https://github.com/user-attachments/assets/c9c10381-f850-4d39-bfd8-9a6595b1d3ed)

**Comment by holipay** [comment] 2024-08-24 06:47
![Uploading 图片2.png…]()

**Comment by 0x2E** [comment] 2024-08-24 10:32
Notifications should be stacked when the mouse is not hovering over them. The stack will not block the button because there is enough space above it.

I tried all my local cases, including sm/md/lg devices and web page zoom in/out, but failed to reproduce this issue.

I'm going to close this issue until we encounter more similar issues.

**Closed by 0x2E** 2024-08-24 10:32 UTC

**Comment by holipay** [comment] 2024-08-25 01:41
os: windows 11 
Display resolution: 1920*1080. 
The system text is scaled by 150%. 
Edge browser zoom 100%. 
Fusion runs locally: http://127.0.0.1:8080/

**Comment by holipay** [comment] 2024-08-26 03:34
Most of the time I need to press the read button to quickly turn the page. In order to ensure that the content of each page of 10 lines is displayed within the visual range of the web page, there is not enough space for the read button. The problem now is that whenever I press the read button, I get blocked by a pop-up window and can't quickly press the read button again.

Although zooming the browser page can avoid the location of the pop-up window, it will make the font shrink and affect the reading.

I hope the pop-up page doesn't come close to this button, just center the pop-up window.

（大多数时候我需要按已读按钮快速翻页。为了保证每页10行内容都显示在网页的可视范围内，导致留给已读按钮的空间不足。现在的问题是，每当我按已读按钮时候，都被弹窗挡住，无法快速再按已读按钮。

虽然缩放浏览器页面可以避开弹窗遮挡的位置，但会使得字体缩小影响阅读。

我希望弹出页面不要靠近这个按钮，把弹窗居中就可以。）

**Comment by 0x2E** [comment] 2024-08-26 04:28
Thanks for the context. The changes will be included in the next release.
